// File generated by FlutterFire CLI (mock/skeleton for compilation).
// Replace these dummy values with your actual Firebase configuration,
// or run `flutterfire configure` to overwrite this file automatically.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIc_ObWVFGTd9OnkxqvlIFp7JjPyDM4t0',
    appId: '1:514349178076:web:2d0a64dff36e2fc6ba6819',
    messagingSenderId: '514349178076',
    projectId: 'fir-p-57bdc',
    authDomain: 'fir-p-57bdc.firebaseapp.com',
    storageBucket: 'fir-p-57bdc.firebasestorage.app',
    measurementId: 'G-ZCMN2STFR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXjzGoUZVyISPLug4ZeovvBPr6vAJSxWw',
    appId: '1:514349178076:android:5a6b7c8d9e0f1a2b3c4d',
    messagingSenderId: '514349178076',
    projectId: 'fir-p-57bdc',
    storageBucket: 'fir-p-57bdc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLR8d-mub_0d6_71j3GmZhnfCEK0apuBc',
    appId: '1:514349178076:ios:bad57bdc45b7206bba6819',
    messagingSenderId: '514349178076',
    projectId: 'fir-p-57bdc',
    storageBucket: 'fir-p-57bdc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLR8d-mub_0d6_71j3GmZhnfCEK0apuBc',
    appId: '1:514349178076:ios:bad57bdc45b7206bba6819',
    messagingSenderId: '514349178076',
    projectId: 'fir-p-57bdc',
    storageBucket: 'fir-p-57bdc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdgtj18vlyVhrqDLW5UUx1tiJy9fIje6U',
    appId: '1:514349178076:web:25a072ce74402057ba6819',
    messagingSenderId: '514349178076',
    projectId: 'fir-p-57bdc',
    authDomain: 'fir-p-57bdc.firebaseapp.com',
    storageBucket: 'fir-p-57bdc.firebasestorage.app',
    measurementId: 'G-HWHMS7YF4J',
  );
}
